version: 2
updates:
  - package-ecosystem: npm
    directory: '/04-automation/ui'
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      dev-dependencies:
        dependency-type: development
  - package-ecosystem: npm
    directory: '/04-automation/api'
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      dev-dependencies:
        dependency-type: development
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: weekly
